"""Bounded HTTP contracts shared by the Gemma service endpoints."""

from pydantic import BaseModel, ConfigDict, Field


class FrozenContract(BaseModel):
    """Prevent request or response mutation after validation."""

    model_config = ConfigDict(frozen=True)


class HealthResponse(FrozenContract):
    """Minimal unauthenticated liveness information."""

    status: str
    ready: bool


class ModelInfo(FrozenContract):
    """Safe metadata for the single model loaded by this service."""

    id: str
    revision: str
    backend: str = "transformers"
    ready: bool


class ModelsResponse(FrozenContract):
    """Model discovery response used by ``algohint doctor``."""

    data: tuple[ModelInfo, ...]


class HintRequest(FrozenContract):
    """One bounded text-only request; media and arbitrary generation options are excluded."""

    model: str = Field(min_length=1, max_length=200)
    system_instructions: str = Field(min_length=1, max_length=8_192)
    learner_context: str = Field(min_length=1, max_length=65_536)


class HintResponse(FrozenContract):
    """Validated text generated by the configured model."""

    model: str
    text: str = Field(min_length=1, max_length=1_200)


class ReviewRequest(HintRequest):
    """Review generation uses the same bounded, option-free transport fields."""


class ReviewResponse(FrozenContract):
    """Structured-review JSON text validated again by the caller."""

    model: str
    text: str = Field(min_length=1, max_length=4_000)
